name: Run tests as part of downstream testing process

on:
  repository_dispatch:
    types: [downstream-testing]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Repository Dispatch Triggered
        run: |
          echo "Workflow triggered successfully by repository dispatch action!"
